import type { Account, Holding } from "@/types";

export const DUMMY_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    user_id: "user-1",
    name: "키움 일반",
    broker: "키움증권",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "acc-2",
    user_id: "user-1",
    name: "한투 ISA",
    broker: "한국투자증권",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "acc-3",
    user_id: "user-1",
    name: "삼성 연금",
    broker: "삼성증권",
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const DUMMY_HOLDINGS: Holding[] = [
  // 키움 일반
  {
    id: "h-1",
    user_id: "user-1",
    account_id: "acc-1",
    ticker: "005930",
    name: "삼성전자",
    market: "KR",
    quantity: 100,
    avg_price: 72000,
    currency: "KRW",
    created_at: "",
    updated_at: "",
  },
  {
    id: "h-2",
    user_id: "user-1",
    account_id: "acc-1",
    ticker: "000660",
    name: "SK하이닉스",
    market: "KR",
    quantity: 30,
    avg_price: 180000,
    currency: "KRW",
    created_at: "",
    updated_at: "",
  },
  {
    id: "h-3",
    user_id: "user-1",
    account_id: "acc-1",
    ticker: "AAPL",
    name: "Apple",
    market: "US",
    quantity: 10,
    avg_price: 190,
    currency: "USD",
    created_at: "",
    updated_at: "",
  },
  // 한투 ISA
  {
    id: "h-4",
    user_id: "user-1",
    account_id: "acc-2",
    ticker: "005930",
    name: "삼성전자",
    market: "KR",
    quantity: 50,
    avg_price: 68000,
    currency: "KRW",
    created_at: "",
    updated_at: "",
  },
  {
    id: "h-5",
    user_id: "user-1",
    account_id: "acc-2",
    ticker: "035720",
    name: "카카오",
    market: "KR",
    quantity: 80,
    avg_price: 52000,
    currency: "KRW",
    created_at: "",
    updated_at: "",
  },
  {
    id: "h-6",
    user_id: "user-1",
    account_id: "acc-2",
    ticker: "NVDA",
    name: "NVIDIA",
    market: "US",
    quantity: 5,
    avg_price: 850,
    currency: "USD",
    created_at: "",
    updated_at: "",
  },
  // 삼성 연금
  {
    id: "h-7",
    user_id: "user-1",
    account_id: "acc-3",
    ticker: "005930",
    name: "삼성전자",
    market: "KR",
    quantity: 200,
    avg_price: 65000,
    currency: "KRW",
    created_at: "",
    updated_at: "",
  },
  {
    id: "h-8",
    user_id: "user-1",
    account_id: "acc-3",
    ticker: "AAPL",
    name: "Apple",
    market: "US",
    quantity: 15,
    avg_price: 175,
    currency: "USD",
    created_at: "",
    updated_at: "",
  },
  {
    id: "h-9",
    user_id: "user-1",
    account_id: "acc-3",
    ticker: "MSFT",
    name: "Microsoft",
    market: "US",
    quantity: 8,
    avg_price: 380,
    currency: "USD",
    created_at: "",
    updated_at: "",
  },
];

/** 달러→원 환율 (더미) */
export const DUMMY_USD_KRW = 1380;

/** 더미 현재가 (ticker → 현재가, KRW or USD 기준) */
export const DUMMY_PRICES: Record<string, number> = {
  "005930": 74500,
  "000660": 192000,
  "035720": 48000,
  AAPL: 210,
  NVDA: 950,
  MSFT: 415,
};
